baseURL = "http://blog.abhilashbabuj.com"
languageCode = 'en-us'
title = 'Abhilash Babu'
theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2


[params]
  colortheme = "dark"
  rss = true

  mainSection = "posts"
  postsOnHomePage = 5
